### ISSUE TITLE
XMLHttpRequest blocked by CORS policy

### ISSUE THREAD

**Issue by RyanVillenaUCR** [Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey#23]
Goal of [this commit](https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/commit/17db6689ae0c6d823ed4175decc28ab28d1db591) was to make the API request to [MyGasFeed](http://www.mygasfeed.com/) using a hardcoded location, and print the top 5 gas stations to the console and to the screen. ([Here's the URL](http://devapi.mygasfeed.com/stations/radius/33.9760506/-117.32105179999999/20/reg/distance/rfej9napna.json) for this specific API call. The API documentation, or at least their sorry excuse for it, is [here](http://www.mygasfeed.com/keys/api).)

To reproduce the error, checkout [RyanVillena/get-gas-station-data](https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/tree/RyanVillena/get-gas-station-data), deploy via local host, click the "FIND!" button, and check the console using Inspect Element. [GasStationData.js:164](https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/blob/e630f2a7c9d95a142da85a02aa19294d6c5687c6/src/components/GasStationData.js#L164) should print an object with a large array of gas stations. There is an error in my console that reads as follows:

> `Access to XMLHttpRequest at 'http://devapi.mygasfeed.com/stations/radius/33.9760506/-117.32105179999999/20/reg/distance/rfej9napna.json?' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I'm not sure what this means, but **some issue with headers is preventing the remote host from sending us data.** I'm using `XMLHttpRequest()` to send the HTTP GET request; see [GasStationData.js:148](https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/blob/e630f2a7c9d95a142da85a02aa19294d6c5687c6/src/components/GasStationData.js#L148) to see the code, or the [tutorial](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction) I used to write it.

One last thing I found out: apparently, launching Chrome in an "insecure mode" enables this data to get through. This sometimes works, but is not feasible for users who shouldn't have to do so. To use this yourself, build and deploy locally as usual, but access Chrome using:

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -incognito --disable-web-security --disable-gpu --user-data-dir=%LOCALAPPDATA%\Google\chromeTemp`

Then, go to `localhost:8080` as usual. This sometimes lets the data go through on my machine, sometimes doesn't.

**Comment by MichaelJBradley** [comment]
Would it be feasible to download the database and then upload it to Firebase like we did with the React Starter Project? It seems to me that the issue is caused by the database not allowing us to access it, but if it's on our own Firebase we could circumvent that.

**Comment by RyanVillenaUCR** [comment]
We'd have to copy the entire database to make that work, and there isn't a way to query for that. We can only query for a location (longitude + latitude) and all locations within a 50-mi radius of that specific coordinate pair.
I have a hunch that there's some kind of setting with the actual HTTP request that needs to be fixed. I'll look into it and report during our scrum meeting later tonight.

**Comment by RyanVillenaUCR** [comment]
Sometimes, I'm getting some additional output from the console when this error occurs. I'm logging this extra message here so that we can reference it later:

> `GasStationData.js:152 Cross-Origin Read Blocking (CORB) blocked cross-origin response http://devapi.mygasfeed.com/stations/radius/33.9760506/-117.32105179999999/20/reg/distance/rfej9napna.json? with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

**Comment by RyanVillenaUCR** [comment]
Found [this article online](https://www.chromium.org/Home/chromium-security/corb-for-developers) about this exact issue. It's a security feature intended to block fishy-looking HTTP requests, such as those with faulty headers. I suspect our database is triggering this security feature because it's old and hasn't been maintained.

I'm submitting the following bug report to Chrome in the hopes that someone at Google is sympathetic to our cause:

![mygasfeed_chromium_bug_report](https://user-images.githubusercontent.com/32404733/68171616-59fcea00-ff29-11e9-9d8a-7184bfaca3d1.JPG)

I'll read more into this issue for the moment, but as of right now **this issue is still unresolved.**

**Comment by RyanVillenaUCR** [comment]
Here's a temporary fix that allows us to actively work on this project: **start Chrome in unsafe mode.** To do this for Chrome on Windows, launch using the following switches:

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" localhost:8080 -incognito --disable-web-security --disable-gpu --user-data-dir=%LOCALAPPDATA%\Google\chromeTemp`

**Comment by RyanVillenaUCR** [comment]
Unfortunately, [Google staff have confirmed that this is a server-side issue:](https://bugs.chromium.org/p/chromium/issues/detail?id=1021366#c7)

![image](https://user-images.githubusercontent.com/32404733/68468965-02cb7380-01ce-11ea-9c16-54191f0fff43.png)

Unfortunately for us, this means that **the unsafe Chrome workaround is all we have** if we stick to real-time MyGasFeed queries. This isn't so bad for development, but does make a proper release impossible since users would need to use unsafe Chrome every time they'd use our site.

To reiterate from [this post](https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/issues/23#issue-516725525), the workaround is to launch Chrome using the following:

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" -incognito --disable-web-security --disable-gpu --user-data-dir=%LOCALAPPDATA%\Google\chromeTemp`

I recommend **making a desktop shortcut** and using this line as its path. This works on Windows; a similar solution should be possible for macOS users.
