### ISSUE TITLE
Map doesnt update with filters

### ISSUE THREAD

**Issue by EdCarrasco** [Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey#44]
The `<MapContainer>` is not receiving the filtered stations data. Note that `<StationsList>` does receive the `selectedFilters `so that it can filter `stationsData`.
https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/blob/24f2974ea4274682de7be3ac06c70255fd865300/src/components/GasStationData.js#L158-L170

Suggestion: Move the code that filters to `<GasStationsContainer>` and then pass the filtered gas stations to `<MapContainer>` and `<StationsList>`.
https://github.com/Magnum-Opus-2-0/Rooty-Tooty-Gas-Computey/blob/24f2974ea4274682de7be3ac06c70255fd865300/src/components/GasStationData.js#L192-L208

**Comment by MichaelJBradley** [comment]
Closed by #40
